In [10]:
import os
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import datetime

# Cấu hình giao diện đồ thị
sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

In [ ]:
# path="/home/slow_data/Air_Quality/filtered_envisoft_air_quality_weather_data.csv"
path="/home/slow_data/Air_Quality/IQAir_air_quality.csv"

In [12]:
df_aqi = pd.read_csv(path)
df_aqi.head()

,timestamp,station_name,longitude,latitude,aqi,WHO_exposure,PM2.5 (µg/m³),PM10 (µg/m³),O3 (µg/m³),NO2 (µg/m³),SO2 (µg/m³),CO (µg/m³),condition,temperature (°),humidity (%),pressure,wind_speed (km/h),wind_direction
0,2025-04-17 01:00:00,Hà Nội: Đại Học Bách Khoa cổng Parabol đường ...,105.8418,21.005200,167,15.6,78.1,215.0,62.8,9.6,8.2,NaN,Nhiều mây,23,86,1007,13.2,135
1,2025-04-17 01:00:00,Hà Nội: Công viên hồ điều hòa Nhân Chính Khuấ...,105.7947,21.003100,154,12.1,60.3,204.5,10.2,2.5,6.5,2.0,Nhiều mây,23,86,1007,13.4,136
2,2025-04-17 01:00:00,Minh Khai - Bắc Từ Liêm,105.7400,21.050000,132,5.2,26.2,218.7,21.0,NaN,0.1,1.4,Mưa,23,84,1007,12.3,132
3,2025-04-17 01:00:00,Vũng Tàu: Ngã tư Giếng nước - Tp.Vũng Tàu (KK),107.0844,10.367976,83,5.2,26.2,66.6,73.5,3.9,6.2,0.1,Nhiều mây,27,83,1010,19.0,103
4,2025-04-17 01:00:00,Hải Dương: UBND TP. Hải Dương - 106 Đường Trần...,106.3357,20.938100,144,10.6,53.0,147.4,48.2,1.0,1.3,2.2,Nhiều mây,21,88,1007,11.7,119

In [ ]:
# QB_filter = df_aqi[df_aqi['Name'] == 'Quảng Bình: KKT Hòn La (KK)']
# QB_filter.head()

# Extract AOD for stations

In [14]:
import rasterio
import glob
from  pathlib import Path

In [15]:
# unique_stations = df_aqi['Name'].unique()
# station_df = df_aqi.groupby('Name')[['ID','Latitude', 'Longitude']].first().reset_index()

unique_stations = df_aqi['station_name'].unique()
station_df = df_aqi.groupby('station_name')[['latitude', 'longitude']].first().reset_index()

In [16]:
station_df

                                         station_name   latitude   longitude
0    Công viên hồ điều hòa Nhân Chính, Khuất Duy Tiến  21.003100  105.794700
1                                                 FPT  10.841600  106.809100
2                                    HCM - FPT Thuduc  10.841600  106.809100
3                           Hà Nội: Chi cục BVMT (KK)  21.015250  105.800130
4   Hà Nội: Công viên hồ điều hòa Nhân Chính  Khuấ...  21.003100  105.794700
5   Hà Nội: TT giao lưu văn hóa phố cổ - Hoàn Kiếm...  21.035584  105.852771
6   Hà Nội: Đại Học Bách Khoa cổng Parabol đường ...  21.005200  105.841800
7   Hải Dương: UBND TP. Hải Dương - 106 Đường Trần...  20.938100  106.335700
8                                        IQAir Ha Noi  21.067900  105.826200
9                        IQAir Vietnam - Saigon Pearl  10.790500  106.718700
10                            Minh Khai - Bắc Từ Liêm  21.050000  105.740000
11                                Office IQAir Ha Noi  21.069000  105.826300
12                Quảng Bình: Khu kinh tế Hòn La (KK)  17.932938  106.496620
13  Thái Bình: Cầu Thái Bình - Đ. Trần Thái Tông -...  20.457800  106.343900
14  Thái nguyên: Đường Hùng Vương - Tp Thái Nguyên...  21.593151  105.843104
15           Thừa Thiên Huế: 83 đường Hùng Vương (KK)  16.462260  107.596351
16                        Trà Vinh: Tp. Trà Vinh (KK)   9.923886  106.339604
17     Vũng Tàu: Ngã tư Giếng nước - Tp.Vũng Tàu (KK)  10.367976  107.084400
18       ĐH Bách Khoa - cổng Parabol đường Giải Phóng  21.005200  105.841800

In [ ]:
aod_dir = "/home/slow_data/Air_Quality/AOD/L2_AOD"
OUTPUT_DIR = "/home/slow_data/Air_Quality/AOD/station_aod/IQAir_stations"

aod_path = Path(aod_dir)

In [ ]:
import os
import glob
import rasterio
import pandas as pd
import numpy as np

# Setup output directory to keep things organized
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Define the pattern
pattern = os.path.join(aod_dir, r'2025??/*/*/aod_vietnam_NC_H??_*_L2ARP031_FLDK.*.tif')
print("Search pattern:", pattern)
files = glob.glob(pattern)
files.sort() # Good practice to process in order
print(f"Found {len(files)} files.")

# Define the columns we want in the final CSVs
band_names = ['AOT', 'Uncertainty', 'AE', 'QA_flag', 'SSA', 'RF']
columns = ['timestamp'] + band_names

for aod_file in files:
    print("Processing file: ", aod_file)
    
    try:
        # 1. Parse Timestamp
        filename = os.path.basename(aod_file)
        parts = filename.split("_")
        timestamp = parts[4] + "_" + parts[5]

        # 2. Read Image Data
        with rasterio.open(aod_file) as src:
            # Read all required bands at once to keep memory handy
            # Bands are 1-indexed in rasterio
            bands_data = [src.read(i) for i in range(1, 7)] 
            
            # 3. Iterate through each station
            for _, row in station_df.iterrows():
                # station_id = str(row['ID'])
                # lon, lat = row["Longitude"], row["Latitude"]

                station_id = str(row['station_name'])
                lon, lat = row["longitude"], row["latitude"]
                
                # Define the output file path for this specific station
                station_csv_path = os.path.join(OUTPUT_DIR, f"{station_id}.csv")
                
                # timestamp = pd.to_datetime(timestamp, format='%Y%m%d_%H%M')
                extracted_values: dict[str, object] = {'timestamp': timestamp}
                
                try:
                    # Get pixel coordinates
                    rowcol = src.index(lon, lat)
                    
                    # Extract data for all bands
                    for i, name in enumerate(band_names):
                        # bands_data is 0-indexed list, so i=0 corresponds to Band 1
                        val = bands_data[i][rowcol[0], rowcol[1]]
                        extracted_values[name] = val
                        
                except Exception as e:
                    # If coordinate is out of bounds or error occurs, ensure band keys remain NaN
                    for name in band_names:
                        extracted_values[name] = np.nan

                # 4. Save to CSV (Append Mode)
                new_df = pd.DataFrame([extracted_values])
                
                # Check if file exists to determine if we need to write the header
                file_exists = os.path.isfile(station_csv_path)
                
                # mode='a' appends to the file instead of overwriting
                new_df.to_csv(station_csv_path, mode='a', header=not file_exists, index=False)

        print(f"✅ Processed timestamp {timestamp}")

    except Exception as e:
        print(f"❌ Error processing file {aod_file}: {e}")

print("All processing complete.")

Search pattern: /home/slow_data/Air_Quality/AOD/L2_AOD/2025??/*/*/aod_vietnam_NC_H??_*_L2ARP031_FLDK.*.tif
Found 47524 files.
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/00/aod_vietnam_NC_H09_20250101_0000_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0000
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/00/aod_vietnam_NC_H09_20250101_0010_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0010
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/00/aod_vietnam_NC_H09_20250101_0020_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0020
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/00/aod_vietnam_NC_H09_20250101_0030_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0030
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/00/aod_vietnam_NC_H09_20250101_0040_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0040
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/00/aod_vietnam_NC_H09_20250101_0050_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0050
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/01/aod_vietnam_NC_H09_20250101_0100_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0100
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/01/aod_vietnam_NC_H09_20250101_0110_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0110
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/01/aod_vietnam_NC_H09_20250101_0120_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0120
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/01/aod_vietnam_NC_H09_20250101_0130_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0130
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/01/aod_vietnam_NC_H09_20250101_0140_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0140
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/01/aod_vietnam_NC_H09_20250101_0150_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0150
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/02/aod_vietnam_NC_H09_20250101_0200_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0200
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/02/aod_vietnam_NC_H09_20250101_0210_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0210
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/02/aod_vietnam_NC_H09_20250101_0220_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0220
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/02/aod_vietnam_NC_H09_20250101_0230_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0230
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/02/aod_vietnam_NC_H09_20250101_0250_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0250
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/03/aod_vietnam_NC_H09_20250101_0300_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0300
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/03/aod_vietnam_NC_H09_20250101_0310_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0310
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/03/aod_vietnam_NC_H09_20250101_0320_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0320
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/03/aod_vietnam_NC_H09_20250101_0330_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0330
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/03/aod_vietnam_NC_H09_20250101_0340_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0340
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/03/aod_vietnam_NC_H09_20250101_0350_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0350
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/04/aod_vietnam_NC_H09_20250101_0400_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0400
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/04/aod_vietnam_NC_H09_20250101_0410_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0410
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/04/aod_vietnam_NC_H09_20250101_0420_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0420
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/04/aod_vietnam_NC_H09_20250101_0430_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0430
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/04/aod_vietnam_NC_H09_20250101_0440_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0440
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/04/aod_vietnam_NC_H09_20250101_0450_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0450
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/05/aod_vietnam_NC_H09_20250101_0500_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0500
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/05/aod_vietnam_NC_H09_20250101_0510_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0510
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/05/aod_vietnam_NC_H09_20250101_0520_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0520
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/05/aod_vietnam_NC_H09_20250101_0530_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0530
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/05/aod_vietnam_NC_H09_20250101_0540_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0540
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/05/aod_vietnam_NC_H09_20250101_0550_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0550
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/06/aod_vietnam_NC_H09_20250101_0600_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0600
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/06/aod_vietnam_NC_H09_20250101_0610_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0610
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/06/aod_vietnam_NC_H09_20250101_0620_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0620
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/06/aod_vietnam_NC_H09_20250101_0630_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0630
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/06/aod_vietnam_NC_H09_20250101_0640_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0640
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/06/aod_vietnam_NC_H09_20250101_0650_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0650
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/07/aod_vietnam_NC_H09_20250101_0700_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0700
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/07/aod_vietnam_NC_H09_20250101_0710_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0710
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/07/aod_vietnam_NC_H09_20250101_0720_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0720
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/07/aod_vietnam_NC_H09_20250101_0730_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0730
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/07/aod_vietnam_NC_H09_20250101_0740_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0740
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/07/aod_vietnam_NC_H09_20250101_0750_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0750
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/08/aod_vietnam_NC_H09_20250101_0800_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0800
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/08/aod_vietnam_NC_H09_20250101_0810_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0810
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/08/aod_vietnam_NC_H09_20250101_0820_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0820
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/08/aod_vietnam_NC_H09_20250101_0830_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0830
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/08/aod_vietnam_NC_H09_20250101_0840_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0840
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/08/aod_vietnam_NC_H09_20250101_0850_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0850
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/09/aod_vietnam_NC_H09_20250101_0900_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0900
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/09/aod_vietnam_NC_H09_20250101_0910_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0910
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/09/aod_vietnam_NC_H09_20250101_0920_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0920
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/09/aod_vietnam_NC_H09_20250101_0930_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0930
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/09/aod_vietnam_NC_H09_20250101_0940_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0940
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/09/aod_vietnam_NC_H09_20250101_0950_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_0950
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/10/aod_vietnam_NC_H09_20250101_1000_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1000
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/10/aod_vietnam_NC_H09_20250101_1010_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1010
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/10/aod_vietnam_NC_H09_20250101_1020_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1020
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/10/aod_vietnam_NC_H09_20250101_1030_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1030
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/10/aod_vietnam_NC_H09_20250101_1040_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1040
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/10/aod_vietnam_NC_H09_20250101_1050_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1050
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/11/aod_vietnam_NC_H09_20250101_1100_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1100
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/11/aod_vietnam_NC_H09_20250101_1110_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1110
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/11/aod_vietnam_NC_H09_20250101_1120_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1120
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/11/aod_vietnam_NC_H09_20250101_1130_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1130
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/11/aod_vietnam_NC_H09_20250101_1140_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1140
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/11/aod_vietnam_NC_H09_20250101_1150_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1150
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/12/aod_vietnam_NC_H09_20250101_1200_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1200
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/12/aod_vietnam_NC_H09_20250101_1210_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1210
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/12/aod_vietnam_NC_H09_20250101_1220_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1220
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/12/aod_vietnam_NC_H09_20250101_1230_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1230
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/12/aod_vietnam_NC_H09_20250101_1240_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1240
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/12/aod_vietnam_NC_H09_20250101_1250_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1250
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/13/aod_vietnam_NC_H09_20250101_1300_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1300
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/13/aod_vietnam_NC_H09_20250101_1310_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1310
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/13/aod_vietnam_NC_H09_20250101_1320_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1320
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/13/aod_vietnam_NC_H09_20250101_1330_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1330
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/13/aod_vietnam_NC_H09_20250101_1340_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1340
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/13/aod_vietnam_NC_H09_20250101_1350_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1350
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/14/aod_vietnam_NC_H09_20250101_1400_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1400
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/14/aod_vietnam_NC_H09_20250101_1410_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1410
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/14/aod_vietnam_NC_H09_20250101_1420_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1420
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/14/aod_vietnam_NC_H09_20250101_1430_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1430
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/14/aod_vietnam_NC_H09_20250101_1450_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1450
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/15/aod_vietnam_NC_H09_20250101_1500_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1500
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/15/aod_vietnam_NC_H09_20250101_1510_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1510
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/15/aod_vietnam_NC_H09_20250101_1530_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1530
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/15/aod_vietnam_NC_H09_20250101_1540_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1540
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/15/aod_vietnam_NC_H09_20250101_1550_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1550
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/16/aod_vietnam_NC_H09_20250101_1600_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1600
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/16/aod_vietnam_NC_H09_20250101_1610_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1610
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/16/aod_vietnam_NC_H09_20250101_1620_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1620
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/16/aod_vietnam_NC_H09_20250101_1630_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1630
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/16/aod_vietnam_NC_H09_20250101_1640_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1640
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/16/aod_vietnam_NC_H09_20250101_1650_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1650
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/17/aod_vietnam_NC_H09_20250101_1700_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1700
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/17/aod_vietnam_NC_H09_20250101_1710_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1710
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/17/aod_vietnam_NC_H09_20250101_1720_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1720
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/17/aod_vietnam_NC_H09_20250101_1730_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1730
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/17/aod_vietnam_NC_H09_20250101_1740_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1740
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/17/aod_vietnam_NC_H09_20250101_1750_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1750
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/18/aod_vietnam_NC_H09_20250101_1800_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1800
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/18/aod_vietnam_NC_H09_20250101_1810_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1810
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/18/aod_vietnam_NC_H09_20250101_1820_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1820
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/18/aod_vietnam_NC_H09_20250101_1830_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1830
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/18/aod_vietnam_NC_H09_20250101_1840_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1840
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/18/aod_vietnam_NC_H09_20250101_1850_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1850
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/19/aod_vietnam_NC_H09_20250101_1900_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1900
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/19/aod_vietnam_NC_H09_20250101_1910_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1910
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/19/aod_vietnam_NC_H09_20250101_1920_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1920
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/19/aod_vietnam_NC_H09_20250101_1930_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1930
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/19/aod_vietnam_NC_H09_20250101_1940_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1940
Processing file:  /home/slow_data/Air_Quality/AOD/L2_AOD/202501/01/19/aod_vietnam_NC_H09_20250101_1950_L2ARP031_FLDK.02401_02401.tif
✅ Processed timestamp 20250101_1950

In [19]:
df_aod = pd.read_csv("/home/slow_data/Air_Quality/AOD/station_aod/31390903576425084107499649578.csv", parse_dates=[0])

In [20]:
df_aod.head()

            timestamp  AOT  Uncertainty  AE  QA_flag  SSA  RF
0 2025-01-01 07:00:00  NaN          NaN NaN   5112.0  NaN NaN
1 2025-01-01 07:10:00  NaN          NaN NaN   5112.0  NaN NaN
2 2025-01-01 07:20:00  NaN          NaN NaN   5112.0  NaN NaN
3 2025-01-01 07:30:00  NaN          NaN NaN   5112.0  NaN NaN
4 2025-01-01 07:40:00  NaN          NaN NaN   5112.0  NaN NaN

In [21]:
df_aod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47524 entries, 0 to 47523
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    47524 non-null  datetime64[ns]
 1   AOT          1554 non-null   float64
 2   Uncertainty  1549 non-null   float64
 3   AE           1549 non-null   float64
 4   QA_flag      47524 non-null  float64
 5   SSA          1549 non-null   float64
 6   RF           1549 non-null   float64
dtypes: datetime64[ns](1), float64(6)
memory usage: 2.5 MB

In [22]:
import pandas as pd
import glob
import os

# Get all CSV files
csv_files = glob.glob(os.path.join(OUTPUT_DIR, "*.csv"))
print(f"Found {len(csv_files)} files to update.")

for file_path in csv_files:
    try:
        # 1. Read the CSV
        df = pd.read_csv(file_path)

        df['timestamp'] = pd.to_datetime(df['timestamp'], format='%Y%m%d_%H%M')
        
        # 3. Add 7 hours to convert UTC -> GMT+7
        df['timestamp'] = df['timestamp'] + pd.Timedelta(hours=7)

        df['timestamp'] = df['timestamp'].dt.strftime('%Y-%m-%d %H:%M:%S')
        
        # 5. Overwrite the file
        df.to_csv(file_path, index=False)
        
        print(f"Updated {os.path.basename(file_path)}")
        
    except Exception as e:
        print(f"❌ Error updating {file_path}: {e}")

print("✅ Timezone conversion complete.")

Found 19 files to update.
Updated Quảng Bình: Khu kinh tế Hòn La (KK).csv
Updated Hà Nội: Chi cục BVMT (KK).csv
Updated Công viên hồ điều hòa Nhân Chính, Khuất Duy Tiến.csv
Updated Trà Vinh: Tp. Trà Vinh (KK).csv
Updated Hà Nội: Công viên hồ điều hòa Nhân Chính  Khuất Duy Tiến (KK).csv
Updated Minh Khai - Bắc Từ Liêm.csv
Updated Hà Nội: Đại Học Bách Khoa cổng Parabol đường Giải Phóng (KK).csv
Updated HCM - FPT Thuduc.csv
Updated Hà Nội: TT giao lưu văn hóa phố cổ - Hoàn Kiếm - Trạm cảm biến(KK).csv
Updated IQAir Ha Noi.csv
Updated Thái nguyên: Đường Hùng Vương - Tp Thái Nguyên (KK).csv
Updated ĐH Bách Khoa - cổng Parabol đường Giải Phóng.csv
Updated IQAir Vietnam - Saigon Pearl.csv
Updated Vũng Tàu: Ngã tư Giếng nước - Tp.Vũng Tàu (KK).csv
Updated Office IQAir Ha Noi.csv
Updated Thừa Thiên Huế: 83 đường Hùng Vương (KK).csv
Updated FPT.csv
Updated Hải Dương: UBND TP. Hải Dương - 106 Đường Trần Hưng Đạo (KK).csv
Updated Thái Bình: Cầu Thái Bình - Đ. Trần Thái Tông - P. Bồ Xuyên - TP Thái Bình (KK).csv
✅ Timezone conversion complete.